* .doom.d
My personal [[https://github.com/doomemacs/doomemacs][Doom Emacs]] settings.
* Usage
** Clone this repo
#+BEGIN_SRC shell
mv .doom.d .doom.d.bak
git clone https://github.com/haditim/.doom.d
#+END_SRC

** Install Doom Emacs
#+BEGIN_SRC shell
git clone --depth 1 https://github.com/hlissner/doom-emacs ~/.emacs.d
~/.emacs.d/bin/doom install
#+END_SRC

** Reload Doom Emacs
Using ~M-x doom/reload~ inside Emacs or =~/.emacs.d/bin/doom sync= in terminal. This assures that the literal ~config.org~ gets processed.


** Optional: install DejaVuSansCode
My setting will fall back to DejaVu Sans Mono if this font does not exist. The only difference is that [[https://github.com/SSNikolaevich/DejaVuSansCode][DejaVuSansCode]] supports ligatures (set in =:ui ligatures= in doom's =init.el=).

** done!

* Documentation
The [[file:config.org][config file]] is self documenting.

* Optional: extra steps
** Programming languages
*** Python
- Install [[https://github.com/python-lsp/python-lsp-server][pylsp]] ~pip install 'python-lsp-server[all]'~
- Install [[https://github.com/Richardk2n/pylsp-mypy][pylsp-mypy]] ~pip install pylsp-mypy~ for type checking
- Install [[https://github.com/python-rope/pylsp-rope][pylsp-rope]] ~pip install pylsp-rope~ for more refactoring possibilities and code actions. This slowed my emacs significantly, if you see the same, just uninstall it ~pip uninstall pylsp-rope~.
- Install [[https://github.com/python-lsp/python-lsp-black][pylsp-black]] ~pip install python-lsp-black~ for formatting using yapf or blacken

*** Rust
If you want to code in Rust, after installing ~rustup~ run
#+BEGIN_SRC shell
rustup toolchain add nightly
rustup component add rust-src
cargo +nightly install racer
#+END_SRC

*** Angular/Typescript
For having ng2 LSP capabilities run
#+BEGIN_SRC shell
npm install -g @angular/language-service@next typescript  @angular/language-server
#+END_SRC

*** Javascript
Install prettier for prettier-js to work

*** VScode-like html auto completion
#+BEGIN_SRC shell
npm install --global vscode-html-languageserver-bin
#+END_SRC

*** Kotlin
For getting Kotlin to work, you need to install [[https://github.com/fwcd/kotlin-language-server][kotlin-language-server]].

*** Flutter
Install dart and Flutter SDK. To open emulator, run
#+BEGIN_SRC shell
emulator @[emulator_name]
#+END_SRC

*** Vala
To user vala with LSP, install [[https://github.com/vala-lang/vala-language-server#emacs][vala-language-server]].

** Misc
*** Set spell checker language
For changing the dictionary for spell checker, do =M-x ispell-change-dictionary= and switch to the language you want. Don't forget to have =hunspell= dictionaries installed before doing this.

* Useful reads
If you never used vim or Emacs, read these up
- [[https://github.com/hlissner/doom-emacs/blob/develop/docs/index.org][Doom Emacs documentation]]
- [[https://github.com/hlissner/doom-emacs/blob/develop/modules/editor/evil/config.el#L413-L460][vim-unimpaired provided by doom]]
- [[https://github.com/hlissner/doom-emacs/blob/develop/modules/editor/evil/README.org#ported-vim-plugins][Ported vim plugins]] in doom docs
